var critical = require('critical');

critical.generate({
  inline: true,
  base: 'public/',
  src: 'index.html',
  dest: 'index.html',
  minify: true,
  width: 1366,
  height: 768,
  include: [
    ".slick-slider",
    ".slick-list",
    ".slick-list.draggable",
    ".draggable",
    ".slick-list:focus",
    ".slick-track",
    ".slick-slide",
    ".slick-slide img",
    "slick-loading img",
    ".slick-initialized",
    ".slick-initialized .slick-slide",
    ".slick-slide.slick-initialized",
    ".slick-slide.slick-loading",
    ".slick-slide.slick-vertical",
    ".slick-arrow.slick-hidden",
    ".slick-list",
    ".slick-list .slick-loading",
    ".slick-loading",
    ".slick-prev",
    ".slick-next",
    ".slick-slider .slick-track",
    ".slick-slider .slick-list",
    "#slides",
    "#slides .desktop",
    "#slides .mobile",
    ".slide-text",
    ".slide-title",
    ".slide-description",
    ".slide img",
    "lazy",
    ".slide",
    ".showing",
    ".slick-slide",
    "barra-azul",
    ".barra-azul .titular",
    ".barra-azul .subtitular",
    ".fondo-imagen"
  ]
});